// Dữ liệu DEMO dễ thương để hiển thị trước khi founder có nội dung thật.
// Khác với yarns.ts (khung placeholder cho nội dung thật sau này), file này
// dùng để seed nhanh một bộ data đẹp mắt cho mục đích xem demo/giới thiệu.
// Xóa/ghi đè bằng nội dung thật bất cứ lúc nào qua npm run db:seed:demo.
import type {
  AllergyRisk,
  FiberCategory,
  Washability,
  WeightCategory,
} from "../../lib/generated/prisma/client";
import type { YarnSeedData } from "./yarns";

export const demoYarnSeedData: YarnSeedData[] = [
  {
    nameVi: "Len Cotton Baby Mây",
    nameEn: "Baby Cotton Cloud",
    fiberCategory: "plant" as FiberCategory,
    fiberComposition: "100% Cotton sợi mịn",
    weightCategory: "sport" as WeightCategory,
    texture: ["mềm như mây", "mịn tay", "nhẹ"],
    warmth: 2,
    softness: 5,
    durability: 4,
    stretch: 2,
    washability: "machine" as Washability,
    allergyRisk: "low" as AllergyRisk,
    useCases: ["đồ sơ sinh", "mũ/áo cho bé", "đồ chơi nhồi bông"],
    careInstructions: "Giặt máy nước lạnh, không dùng nước xả vải, phơi trong bóng mát.",
    descriptionVi:
      "Sợi cotton mềm mịn được chọn riêng cho làn da nhạy cảm của bé, sờ vào êm như đang ôm một cụm mây nhỏ. Lên màu tươi sáng, đan/móc lên form đẹp mà không bị nặng tay, rất hợp để làm mũ, áo liền hay những món đồ chơi handmade đầu tiên tặng bé yêu.",
    pros: ["Êm dịu, an toàn cho da bé", "Lên màu tươi, giữ form tốt", "Giặt máy được, tiện chăm sóc"],
    cons: ["Không giữ ấm nhiều như len lông động vật"],
    tags: ["cho bé", "người mới", "mùa hè"],
  },
  {
    nameVi: "Len Merino Sữa Non",
    nameEn: "Merino Soft Cream",
    fiberCategory: "animal" as FiberCategory,
    fiberComposition: "100% Merino cừu non",
    weightCategory: "dk" as WeightCategory,
    texture: ["mềm mượt", "ấm áp", "có độ phồng nhẹ"],
    warmth: 5,
    softness: 5,
    durability: 3,
    stretch: 4,
    washability: "hand" as Washability,
    allergyRisk: "low" as AllergyRisk,
    useCases: ["áo len", "khăn choàng", "phụ kiện mùa đông"],
    careInstructions: "Giặt tay nhẹ nhàng với nước lạnh, không vắt xoắn, trải phẳng để khô tự nhiên.",
    descriptionVi:
      "Tên gọi 'Sữa Non' lấy cảm hứng từ chính cảm giác mềm mại, ngọt ngào khi chạm vào sợi — mượt như một ly sữa ấm vào ngày đông. Đây là lựa chọn yêu thích của nhiều thợ đan khi muốn dệt nên một chiếc khăn hoặc áo thật ấm mà vẫn nhẹ nhàng, không gây ngứa.",
    pros: ["Giữ ấm vượt trội", "Mềm mịn, không gây ngứa", "Co giãn tốt, lên form đẹp"],
    cons: ["Giá cao hơn sợi tổng hợp", "Cần giặt tay cẩn thận"],
    tags: ["mùa đông", "cao cấp", "quà tặng"],
  },
  {
    nameVi: "Sợi Acrylic Cầu Vồng",
    nameEn: "Rainbow Acrylic",
    fiberCategory: "synthetic" as FiberCategory,
    fiberComposition: "100% Acrylic",
    weightCategory: "worsted" as WeightCategory,
    texture: ["chắc tay", "hơi bóng nhẹ"],
    warmth: 3,
    softness: 3,
    durability: 5,
    stretch: 3,
    washability: "machine" as Washability,
    allergyRisk: "medium" as AllergyRisk,
    useCases: ["túi xách", "đồ amigurumi", "phụ kiện trang trí"],
    careInstructions: "Giặt máy được, phơi nơi thoáng, tránh ủi trực tiếp lên sợi.",
    descriptionVi:
      "Một hộp màu cầu vồng thu nhỏ cho người mới bắt đầu! Sợi acrylic giá dễ chịu, bền màu, lại có sẵn rất nhiều màu tươi vui — cứ tự do thử nghiệm mẫu mới mà không lo 'tốn'. Đặc biệt hợp để móc amigurumi vì giữ form mũi móc rất rõ nét.",
    pros: ["Giá thành rẻ, dễ tiếp cận", "Nhiều màu sắc tươi sáng", "Bền, ít xù lông, giặt máy thoải mái"],
    cons: ["Kém thoáng khí hơn sợi tự nhiên", "Một số bạn có làn da nhạy cảm có thể hơi ngứa"],
    tags: ["người mới", "giá tốt", "amigurumi"],
  },
  {
    nameVi: "Sợi Tre Mát Lạnh",
    nameEn: "Cool Bamboo",
    fiberCategory: "plant" as FiberCategory,
    fiberComposition: "70% Bamboo, 30% Cotton",
    weightCategory: "fingering" as WeightCategory,
    texture: ["mát tay", "mượt", "có độ rơi nhẹ"],
    warmth: 1,
    softness: 4,
    durability: 3,
    stretch: 2,
    washability: "hand" as Washability,
    allergyRisk: "low" as AllergyRisk,
    useCases: ["áo mùa hè", "khăn voan mỏng", "đồ mặc nhà"],
    careInstructions: "Giặt tay nhẹ, không ngâm lâu, phơi ngang để giữ form, tránh nắng gắt.",
    descriptionVi:
      "Đúng như tên gọi, sợi tre mang lại cảm giác mát lạnh dễ chịu ngay khi chạm vào — lý tưởng cho những món đồ đan mặc vào mùa hè mà vẫn muốn giữ vẻ thanh lịch. Sợi có độ rơi tự nhiên, lên hoa văn ren rất đẹp.",
    pros: ["Thoáng mát, hợp khí hậu nóng", "Kháng khuẩn tự nhiên", "Lên hoa văn ren rất đẹp"],
    cons: ["Độ bền form không cao bằng len động vật", "Cần giặt tay nhẹ nhàng"],
    tags: ["mùa hè", "thanh lịch"],
  },
  {
    nameVi: "Len Mohair Bông Mây",
    nameEn: "Fluffy Mohair Cloud",
    fiberCategory: "animal" as FiberCategory,
    fiberComposition: "70% Mohair, 30% Silk",
    weightCategory: "lace" as WeightCategory,
    texture: ["lông xù mềm", "nhẹ bồng"],
    warmth: 4,
    softness: 4,
    durability: 2,
    stretch: 3,
    washability: "hand" as Washability,
    allergyRisk: "medium" as AllergyRisk,
    useCases: ["áo khoác mỏng", "khăn choàng bông", "điểm nhấn phối sợi"],
    careInstructions: "Giặt tay cực nhẹ, không vò, để khô tự nhiên trên mặt phẳng, tránh chải mạnh khi còn ướt.",
    descriptionVi:
      "Sợi mảnh nhưng 'tóc' lông xù bông như mây, thường được phối cùng một sợi khác để tạo hiệu ứng mờ ảo, lãng mạn cho thành phẩm. Chỉ cần một chút điểm xuyến Mohair Bông Mây, chiếc khăn hay áo khoác của bạn sẽ trông sang trọng hơn hẳn.",
    pros: ["Hiệu ứng lông bông đẹp mắt", "Nhẹ, ấm vừa phải", "Sang trọng khi phối cùng sợi khác"],
    cons: ["Dễ xù rối nếu đan/móc quá chặt tay", "Không hợp với người mới vì hơi khó kiểm soát mũi"],
    tags: ["cao cấp", "trang trí", "phối sợi"],
  },
];
